### PR TITLE
Save the last checkpoint also in a folder as others

### PR DESCRIPTION
**Pull request by ArvinZhuang**
Currently, the last checkpoint is saved in the root folder of other checkpoints. This minor change put the last one also in the same level of folder as others.

### CODE REVIEW

**Comment by luyug** [comment]
The original setup where the last checkpoint data is saved to the folder root is, basically, a carry-over from some Huggingface script. This means, we don't really have a good reason for doing that. On the other hand it is something I used to assume that many people are used to . I wonder if there is a good reason to change the current setup?

**Comment by ArvinZhuang** [comment]
Hi @luyug, thanks for the feedback.

I see its carry-over from Huggingface examples and it really doesn't matter a lot for now. 
The reason that I propose this change is that I am developing an automatic validation toolkit for DRs and I'm taking tevatron as the example to generate DR checkpoints (so my toolkit should be directly usable for tevatron once it's done). This change is just more convenient for my case. I think we can leave this pull requirest here and see if this is necessary later.

**Comment by luyug** [comment]
In that case, one thing we could potentially do is to keep the original setup and store last checkpoint files at root. On top of that, have a folder like `checkpoint_last` where we keep a set of symlinks. Or the other way around, keep the actual files in that folder and the symlinks at root.

**Comment by ArvinZhuang** [comment]
Hi @luyug @MXueguang, here is the DR checkpoints validation toolkit that I mentioned in this pull request: https://github.com/ielab/asyncval/tree/main/examples/msmarco-passage

Tevatron users can just `pip install asyncval` and then follow this example to run DR checkpoint validation generated by tevatron trainer. Any feedback or suggestions?

**Comment by luyug** [comment]
Hi @ArvinZhuang, this looks nice! I will take a closer look at it and see if it can also work with our planned future developments.

BTW, would you like to potentially put an example into the Tevatron's example folder?

**Comment by ArvinZhuang** [comment]
Hi @luyug, yep I definitely would like to add an example in Tevatron as well. I'll do this once I have time. 

and for compatible future tevatron plans, I think as long as the `encode_passage` and `encode_query` APIs in `DenseModelforInference` class keep unchanged, then it will work.

**Comment by ArvinZhuang** [comment]
Hi @luyug, I have added a section in example/READEME.md for Asyncval, feel free to move it in an additional example folder if you like. Also, I undo the changes made before as it will break some examples. So for Asyncval, the problem is still there: an error will raise for the last checkpoint validation as it is not in the same path level as other checkpoints.

**Comment by MXueguang** [comment]
Hi @ArvinZhuang 
I just updated docs in `/examples`, so the current change here will have conflicts.
Do you mind move the asyncval example to `examples/example_asyncval`? then we can merge the PR.

**Comment by ArvinZhuang** [comment]
@MXueguang Hi, I have created the example file.

**Review by MXueguang — APPROVED** [review]

**Pull request merged**
